---
title: "Covid in Switzerland"
description: |
  A short description of the post.
author:
  - name: Mengyun Yang
    url: https://example.com/norajones
date: 08-29-2021
output:
  distill::distill_article:
    self_contained: false
---

```{css, echo = FALSE}
h2{
  color: #325c59;
}
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)
```

```{r packages, message = FALSE}
library(here)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
library(kableExtra)
library(formattable)
library(DT)
library(gt)
library(sf)
library(rworldmap)
library(plotly)
library(leaflet)
library(rjson)
library(geojsonio)
```

```{r read-data}
covid <- read_csv(here("data/COVID19IntCases.csv"))
#poly <- geojson_read(here("data/countries.geojson", what = "sp"))
```
## Data Description

## Data Story

```{r map-data}

# EU contries
eu <- covid %>% 
  filter(geoRegionName %in% c("Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
                          "Croatia", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
                          "Holy See", "Hungary", "Iceland", "Ireland", "Italy", "Latvia", "Liechtenstein", "Lithuania",
                          "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia",
                          "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia",
                          "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", "United Kingdom")) %>% 
  group_by(geoRegionName) %>% 
  summarise(count = sum(entries)) 

# get world map
worldMap <- getMap()

# Select only the index of selected EU countries
indEU <- which(worldMap$NAME %in% eu$geoRegionName)

# Extract longitude and latitude border's coordinates  
europeCoords <- lapply(indEU, function(i){
  df <- data.frame(worldMap@polygons[[i]]@Polygons[[1]]@coords)
  df$region =as.character(worldMap$NAME[i])
  colnames(df) <- list("long", "lat", "region")
  return(df)
})

europeCoords <- do.call("rbind", europeCoords)

#join data
eu_map <- eu %>% 
  rename(region = "geoRegionName") %>% 
  right_join(europeCoords,
             by = "region")
```

```{r map}
map <- ggplot() + 
  geom_polygon(data = eu_map, 
               aes(x = long, 
                   y = lat, 
                   group = region, 
                   fill = count),
               colour = "black", size = 0.1) +
  coord_map(xlim = c(-20, 180),  
            ylim = c(10, 80))+ 
  scale_fill_gradient(name = "Total Covid Cases", 
                      low = "#d3e3fc", 
                      high = "#314455", 
                      na.value = "grey50") +
  theme(#panel.grid.minor = element_line(colour = NA), panel.grid.minor = element_line(colour = NA),
               panel.background = element_rect(fill = "white"),
               axis.text.x = element_blank(),
               axis.text.y = element_blank(), 
               axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(), 
               axis.title = element_blank())
               #rect = element_blank(),
               #plot.margin = unit(0 * c(-1.5, -1.5, -1.5, -1.5), "lines"))

 ggplotly(map)
```

```{r tab-1}
covid %>% 
  mutate(Year = year(date),
         Month = month(date)) %>% 
  filter(geoRegionName == "Switzerland") %>% 
  group_by(Year) %>% 
  summarise("Total Confirmed Cases" = sum(entries)) %>% 
  kable() %>% 
  kable_styling()
```

